name: Validate BDF Metadata

on:
  push:
    branches: [ EC_20250927, 9mo_milestone, main ]
  pull_request:
    branches: [ EC_20250927, 9mo_milestone, main ]

jobs:
  validate-tool:
    # This USES their workflow definition but RUNS in your repo
    uses: ARPA-H-BDF/bdfkb-schema/.github/workflows/ci-validate.yaml@main
    with:
      python-version: '3.9'